
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
  default:
    execution:
    isolation:
      thread:
        timeoutInMilliseconds: 10000
#execution:
#  timeout: enabled
#  isolation:
#    thread:
#      timeoutInMilliseconds: 1000
eureka:
  instance:
    #eureka 注册显示名称
    instanceId: ${spring.application.name}:${random.value}
    #显示ip
    prefer-ip-address: true
    hostname: host-customer
    appname: service-customer
  client:
    serviceUrl:
      defaultZone: http://app-eureka-2:7999/eureka
