spring:
  application:
    name: app-eureka
server:
  port: 7999
eureka:
  instance:
    hostname: app-eureka-2
    #prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://app-eureka-1:8001/eureka
