spring:
  application:
    name: app-eureka
server:
  port: 8001
eureka:
  instance:
    hostname: app-eureka-1
    #prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://app-eureka-2:7999/eureka
    #http://${eureka.instance.hostname}:${server.port}/eureka
