spring:
  application:
    name: app-provider
server:
  port: 8002
eureka:
  instance:
    #eureka 注册显示名称
    instanceId: ${spring.application.name}:${random.value}
    #显示ip
    prefer-ip-address: true
    hostname: host-provider
    appname: service-provider
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
